/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : SCI3.C
**     Project   : mc51_6_3
**     Processor : MCF51AC256ACLK
**     Component : Init_SCI
**     Version   : Component 01.132, Driver 01.18, CPU db: 3.00.053
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 30/03/2011, 06:50 p.m.
**     Abstract  :
**          This bean encapsulates Serial Communications Interface module
**          This modules allows asynchronous communications with peripheral
**          devices and other microcontroller units (MCU).
**     Settings  :
**          Bean name                                      : SCI3
**          Device                                         : SCI1
**          Settings
**            Baud rate divisor                            : 4
**            Baud rate                                    : 65536 baud
**            Loop mode                                    : Disabled
**            Receiver source select                       : Loop mode
**            TxD1 pin direction                           : Input
**            Data Format                                  : 8 bits
**            Stop in Wait mode                            : Disabled
**            Wake up                                      : Idle line wakeup
**            Idle character counting                      : After start bit
**            Parity                                       : None
**            Send break                                   : Disabled
**          Pins
**            RxD pin allocation                           : Enabled
**            RxD pin                                      : PTE1_RGPIO1_RxD1
**            RxD pin signal                               : 
**            TxD pin                                      : PTE0_RGPIO0_TxD1
**            TxD pin signal                               : 
**          Interrupts
**            Tx interrupt
**              Interrupt                                  : Vsci1tx
**              Transmit interrupt                         : Disabled
**              Transmition complete interrupt             : Disabled
**              ISR name                                   : 
**            Rx interrupt                                 : 
**              Interrupt                                  : Vsci1rx
**              Receive interrupt                          : Disabled
**              Idle line interrupt                        : Disabled
**              ISR name                                   : 
**            Error interrupt                              : 
**              Interrupt                                  : Vsci1err
**              Receive framing error interrupt            : Disabled
**              Receive noise error interrupt              : Disabled
**              Receive overrun interrupt                  : Disabled
**              Receive parity error interrupt             : Disabled
**              ISR name                                   : 
**          Initialization                                 : 
**            Call Init in CPU init. code                  : yes
**            Transmitter                                  : Disabled
**            Receiver                                     : Disabled
**     Contents  :
**         Init - void SCI3_Init(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE SCI3. */

#include "SCI3.h"

/*
** ===================================================================
**     Method      :  SCI3_Init (component Init_SCI)
**
**     Description :
**         This method initializes registers of the SCI module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void SCI3_Init(void)
{
  /* SCI1C2: TIE=0,TCIE=0,RIE=0,ILIE=0,TE=0,RE=0,RWU=0,SBK=0 */
  setReg8(SCI1C2, 0x00);               /* Disable the SCI1 module */ 
  (void)getReg8(SCI1S1);               /* Dummy read of the SCI1S1 register to clear flags */
  (void)getReg8(SCI1D);                /* Dummy read of the SCI1D register to clear flags */
  /* SCI1S2: LBKDIF=1,RXEDGIF=1,??=0,RXINV=0,RWUID=0,BRK13=0,LBKDE=0,RAF=0 */
  setReg8(SCI1S2, 0xC0);                
  /* SCI1BDH: LBKDIE=0,RXEDGIE=0,??=0,SBR12=0,SBR11=0,SBR10=0,SBR9=0,SBR8=0 */
  setReg8(SCI1BDH, 0x00);               
  /* SCI1BDL: SBR7=0,SBR6=0,SBR5=0,SBR4=0,SBR3=0,SBR2=1,SBR1=0,SBR0=0 */
  setReg8(SCI1BDL, 0x04);               
  /* SCI1C1: LOOPS=0,SCISWAI=0,RSRC=0,M=0,WAKE=0,ILT=0,PE=0,PT=0 */
  setReg8(SCI1C1, 0x00);                
  /* SCI1C3: R8=0,T8=0,TXDIR=0,TXINV=0,ORIE=0,NEIE=0,FEIE=0,PEIE=0 */
  setReg8(SCI1C3, 0x00);                
  /* SCI1C2: TIE=0,TCIE=0,RIE=0,ILIE=0,TE=0,RE=0,RWU=0,SBK=0 */
  setReg8(SCI1C2, 0x00);                
}

/* END SCI3. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
