/* The contents of this file is automatically generated and contains static
   definitions for some pre-defined modes */
#include "modes.h"
#include "rate.h"

#ifndef DEF_EBANDS31250_64
#define DEF_EBANDS31250_64
static const celt_int16 eBands31250_64[14] = {
0, 3, 6, 9, 12, 15, 18, 22, 26, 31, 38, 45, 64, 64, };
#endif

#ifndef DEF_WINDOW32
#define DEF_WINDOW32
static const celt_word16 window32[32] = {
31, 278, 771, 1503, 2468, 3653, 5044, 6620, 8359, 10231, 12203, 14241, 16304, 18354, 20352, 22260, 24045, 25681, 27144, 28423, 29511, 30410, 31129, 31683, 32092, 32377, 32563, 32674, 32733, 32758, 32766, 32767, };
#endif

#ifndef DEF_ALLOC_VECTORS31250_64
#define DEF_ALLOC_VECTORS31250_64
static const celt_int16 allocVectors31250_64[144] = {
 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
 3,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
 3,  2,  2,  3,  2,  1,  1,  0,  0,  0,  0,  0, 
 4,  3,  3,  4,  3,  2,  1,  1,  0,  0,  0,  0, 
 5,  4,  4,  4,  3,  2,  2,  1,  1,  1,  0,  0, 
 7,  6,  5,  5,  4,  2,  2,  1,  1,  1,  1,  0, 
 8,  8,  6,  5,  4,  2,  2,  2,  3,  2,  3,  0, 
10,  8,  7,  6,  4,  4,  3,  3,  4,  5,  5,  3, 
12, 10,  9,  9,  8,  7,  8,  9,  9,  9, 11,  9, 
13, 12, 13, 13, 11,  9, 10,  8, 10, 11, 17, 14, 
14, 17, 18, 17, 16, 13, 15, 13, 15, 14, 20, 21, 
18, 26, 26, 26, 23, 19, 23, 20, 22, 21, 26, 26, 
};
#endif

#ifndef DEF_ALLOC_CACHE31250_64
#define DEF_ALLOC_CACHE31250_64
static const celt_int16 allocCache_band0_31250_64[MAX_PSEUDO] = {
 0, 42, 67, 84, 97, 107, 116, 123, 129, 134, 139, 143, 147, 151, 154, 158, 161, 166, 171, 175, 179, 183, 186, 190, 193, 198, 203, 207, 211, 215, 218, 222, 225, 230, 235, 239, 243, 247, 250, 254, };
#define allocCache_band1_31250_64 allocCache_band0_31250_64
#define allocCache_band2_31250_64 allocCache_band1_31250_64
static const celt_int16 allocCache_band3_31250_64[MAX_PSEUDO] = {
 0, 42, 67, 84, 97, 107, 116, 123, 129, 134, 139, 143, 147, 151, 154, 158, 161, 166, 171, 175, 179, 183, 186, 190, 193, 198, 203, 207, 211, 215, 218, 222, 225, 230, 235, 239, 243, 247, 250, 254, };
static const celt_int16 allocCache_band4_31250_64[MAX_PSEUDO] = {
 0, 42, 67, 84, 97, 107, 116, 123, 129, 134, 139, 143, 147, 151, 154, 158, 161, 166, 171, 175, 179, 183, 186, 190, 193, 198, 203, 207, 211, 215, 218, 222, 225, 230, 235, 239, 243, 247, 250, 254, };
static const celt_int16 allocCache_band5_31250_64[MAX_PSEUDO] = {
 0, 42, 67, 84, 97, 107, 116, 123, 129, 134, 139, 143, 147, 151, 154, 158, 161, 166, 171, 175, 179, 183, 186, 190, 193, 198, 203, 207, 211, 215, 218, 222, 225, 230, 235, 239, 243, 247, 250, 254, };
static const celt_int16 allocCache_band6_31250_64[MAX_PSEUDO] = {
 0, 48, 80, 104, 122, 136, 148, 159, 168, 176, 183, 190, 196, 201, 206, 211, 215, 223, 231, 237, 243, 249, 254, 259, 263, 271, 279, 285, 291, 297, 302, 307, 311, 319, 327, 333, 339, 345, 350, 355, };
static const celt_int16 allocCache_band7_31250_64[MAX_PSEUDO] = {
 0, 48, 80, 104, 122, 136, 148, 159, 168, 176, 183, 190, 196, 201, 206, 211, 215, 223, 231, 237, 243, 249, 254, 259, 263, 271, 279, 285, 291, 297, 302, 307, 311, 319, 327, 333, 339, 345, 350, 355, };
static const celt_int16 allocCache_band8_31250_64[MAX_PSEUDO] = {
 0, 54, 91, 119, 142, 160, 176, 189, 201, 211, 221, 229, 237, 245, 251, 258, 264, 274, 284, 293, 301, 308, 315, 321, 327, 338, 348, 357, 365, 372, 379, 385, 391, 402, 412, 421, 429, 436, 443, 449, };
static const celt_int16 allocCache_band9_31250_64[MAX_PSEUDO] = {
 0, 61, 106, 142, 172, 197, 219, 238, 254, 270, 283, 296, 307, 318, 328, 337, 346, 362, 377, 390, 401, 412, 423, 432, 441, 457, 472, 485, 497, 508, 536, 545, 555, 572, 586, 599, 611, 622, 632, 641, };
static const celt_int16 allocCache_band10_31250_64[MAX_PSEUDO] = {
 0, 61, 106, 142, 172, 197, 219, 238, 254, 270, 283, 296, 307, 318, 328, 337, 346, 362, 377, 390, 401, 412, 423, 432, 441, 457, 472, 485, 497, 508, 536, 545, 555, 572, 586, 599, 611, 622, 632, 641, };
static const celt_int16 allocCache_band11_31250_64[MAX_PSEUDO] = {
 0, 84, 152, 211, 263, 310, 353, 393, 429, 463, 495, 549, 578, 605, 630, 654, 678, 721, 761, 797, 830, 862, 890, 918, 943, 1003, 1052, 1092, 1129, 1179, 1213, 1242, 1268, 1316, 1360, 1399, 1436, 1468, 1498, 1526, };
static const celt_int16 *allocCache31250_64[12] = {
allocCache_band0_31250_64, allocCache_band1_31250_64, allocCache_band2_31250_64, allocCache_band3_31250_64, allocCache_band4_31250_64, allocCache_band5_31250_64, allocCache_band6_31250_64, allocCache_band7_31250_64, allocCache_band8_31250_64, allocCache_band9_31250_64, allocCache_band10_31250_64, allocCache_band11_31250_64, };
#endif

static const CELTMode mode31250_64_32 = {
0xa110ca7e,	/* marker */
31250,	/* Fs */
32,	/* overlap */
64,	/* mdctSize */
12,	/* nbEBands */
8,	/* pitchEnd */
eBands31250_64,	/* eBands */
26214,	/* ePredCoef */
12,	/* nbAllocVectors */
allocVectors31250_64,	/* allocVectors */
allocCache31250_64,	/* bits */
{128, 0, 0},	/* mdct */
window32,	/* window */
1,	/* nbShortMdcts */
64,	/* shortMdctSize */
{128, 0, 0},	/* shortMdct */
window32,	/* shortWindow */
0,	/* prob */
0xa110ca7e,	/* marker */
};

/* List of all the available modes */
#define TOTAL_MODES 1
static const CELTMode * const static_mode_list[TOTAL_MODES] = {
&mode31250_64_32,
};
