/*
** ###################################################################
**     This code is generated by the Device Initialization Tool.
**     It is overwritten during code generation.
**     USER MODIFICATION ARE PRESERVED ONLY INSIDE INTERRUPT SERVICE ROUTINES
**     OR EXPLICITLY MARKED SECTIONS
**
**     Project   : mc51_6_3
**     Processor : MCF51JM128VLK
**     Version   : Component 01.008, Driver 01.07, CPU db: 3.00.058
**     Datasheet : MCF51JM128RM Rev. 1 1/2008
**     Date/Time : 22/04/2013, 17:22
**     Abstract  :
**         This module contains device initialization code 
**         for selected on-chip peripherals.
**     Contents  :
**         Function "MCU_init" initializes selected peripherals
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################
*/

/* MODULE MCUinit */

#include <MCF51JM128.h>                /* I/O map for MCF51JM128VLK */
#include "MCUinit.h"

/* pragma to disable "possibly unassigned ISR handler" message generated by compiler on definition of ISR without vector number */
#pragma warn_absolute off

/* User declarations and definitions */
/*   Code, declarations and definitions here will be preserved during code generation */
/* End of user declarations and definitions */

/*
** ===================================================================
**     Method      :  __initialize_hardware (component MCF51JM128_80)
**
**     Description :
**         Initialization code for CPU core and a clock source.
** ===================================================================
*/
void __initialize_hardware(void)
{
  /* ### MCF51JM128_80 "Cpu" init code ... */
  /*  PE initialization code after reset */

  /* Common initialization of the write once registers */
  /* SOPT1: COPT=0,STOPE=0,WAITE=1 */
  SOPT1 = 0x10;                                      
  /* SOPT2: COPCLKS=0,COPW=0,USB_BIGEND=0,CLKOUT_EN=0,CMT_CLK_SEL=0,SPI1FE=1,SPI2FE=1,ACIC=0 */
  SOPT2 = 0x06;                                      
  /* SPMSC1: LVWF=0,LVWACK=0,LVWIE=0,LVDRE=1,LVDSE=1,LVDE=1,BGBE=0 */
  SPMSC1 = 0x1C;                                      
  /* SPMSC2: LVDV=0,LVWV=0,PPDF=0,PPDACK=0,PPDC=0 */
  SPMSC2 = 0x00;                                      
  /* Initialization of CPU registers */
  asm {
    /* VBR: ADDRESS=0 */
    clr.l d0
    movec d0,VBR
    /* CPUCR: ARD=0,IRD=0,IAE=0,IME=0,BWD=0,FSD=0 */
    clr.l d0
    movec d0,CPUCR
  }
  /*  System clock initialization */
  /* MCGC2: BDIV=0,RANGE=1,HGO=1,LP=0,EREFS=1,ERCLKEN=1,EREFSTEN=0 */
  MCGC2 = 0x36;                        /* Set MCGC2 register */
  /* MCGC3: DIV32=1 */
  MCGC3 |= (unsigned char)0x10;                      
  /* MCGC1: CLKS=2,RDIV=2,IREFS=0,IRCLKEN=0,IREFSTEN=0 */
  MCGC1 = 0x90;                        /* Set MCGC1 register */
  /* MCGC3: LOLIE=0,PLLS=0,CME=0,DIV32=1,VDIV=8 */
  MCGC3 = 0x18;                        /* Set MCGC3 register */
  /* MCGC4: DMX32=0,DRST_DRS=0 */
  MCGC4 = 0x00;                        /* Set MCGC4 register */
  while(!MCGSC_OSCINIT) {              /* Wait until external reference is stable */
  }
  while(MCGSC_IREFST) {                /* Wait until external reference is selected */
  }
  while((MCGSC & 0x0C) != 0x08) {      /* Wait until external clock is selected as a bus clock reference */
  }
  /* MCGC2: BDIV=0,RANGE=1,HGO=1,LP=1,EREFS=1,ERCLKEN=1,EREFSTEN=0 */
  MCGC2 = 0x3E;                        /* Set MCGC2 register */
  /* MCGC1: CLKS=2,RDIV=3,IREFS=0,IRCLKEN=0,IREFSTEN=0 */
  MCGC1 = 0x98;                        /* Set MCGC1 register */
  /* MCGC3: LOLIE=0,PLLS=0,CME=0,DIV32=0,VDIV=8 */
  MCGC3 = 0x08;                        /* Set MCGC3 register */
  /* MCGC3: LOLIE=0,PLLS=1,CME=0,DIV32=0,VDIV=8 */
  MCGC3 = 0x48;                        /* Set MCGC3 register */
  while(!MCGSC_PLLST) {                /* Wait until PLL is selected */
  }
  /* MCGC2: LP=0 */
  MCGC2 &= (unsigned char)~0x08;                     
  while(!MCGSC_LOCK) {                 /* Wait until PLL is locked */
  }
  /* MCGC1: CLKS=0,RDIV=3,IREFS=0,IRCLKEN=0,IREFSTEN=0 */
  MCGC1 = 0x18;                        /* Set MCGC1 register */
  while((MCGSC & 0x0C) != 0x0C) {      /* Wait until PLL clock is selected as a bus clock reference */
  }
  
  /* INTC_WCR: ENB=0,MASK=0 */
  INTC_WCR = 0x00;                                      
}

/*
** ===================================================================
**     Method      :  MCU_init (component MCF51JM128_80)
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/
void MCU_init(void)
{
  /* SCGC1: CMT=1,TPM2=1,TPM1=0,ADC=1,IIC2=1,IIC1=1,SCI2=1,SCI1=1 */
  SCGC1 = 0xDF;                                      
  /* SCGC2: USB=1,FLS=1,IRQ=1,KBI=1,ACMP=1,RTC=1,SPI2=1,SPI1=1 */
  SCGC2 = 0xFF;                                      
  /* SCGC3: RNGA=1 */
  SCGC3 = 0xFF;                                      
  /* Common initialization of the CPU registers */
  /* PTASE: PTASE7=1,PTASE6=1,PTASE5=1,PTASE4=1,PTASE3=1,PTASE2=1,PTASE1=1,PTASE0=1 */
  PTASE = 0xFF;                                      
  /* PTBSE: PTBSE7=1,PTBSE6=1,PTBSE5=1,PTBSE4=1,PTBSE3=1,PTBSE2=1,PTBSE1=1,PTBSE0=1 */
  PTBSE = 0xFF;                                      
  /* PTCSE: PTCSE7=1,PTCSE6=1,PTCSE5=1,PTCSE4=1,PTCSE3=1,PTCSE2=1,PTCSE1=1,PTCSE0=1 */
  PTCSE = 0xFF;                                      
  /* PTDSE: PTDSE7=1,PTDSE6=1,PTDSE5=1,PTDSE4=1,PTDSE3=1,PTDSE2=1,PTDSE1=1,PTDSE0=1 */
  PTDSE = 0xFF;                                      
  /* PTESE: PTESE7=1,PTESE6=1,PTESE5=1,PTESE4=1,PTESE3=1,PTESE2=1,PTESE1=1,PTESE0=1 */
  PTESE = 0xFF;                                      
  /* PTFSE: PTFSE7=1,PTFSE6=1,PTFSE5=1,PTFSE4=1,PTFSE3=1,PTFSE2=1,PTFSE1=1,PTFSE0=1 */
  PTFSE = 0xFF;                                      
  /* PTGSE: PTGSE7=1,PTGSE6=1,PTGSE5=1,PTGSE4=1,PTGSE3=1,PTGSE2=1,PTGSE1=1,PTGSE0=1 */
  PTGSE = 0xFF;                                      
  /* PTHSE: PTHSE4=1,PTHSE3=1,PTHSE2=1,PTHSE1=1,PTHSE0=1 */
  PTHSE |= (unsigned char)0x1F;                      
  /* PTJSE: PTJSE4=1,PTJSE3=1,PTJSE2=1,PTJSE1=1,PTJSE0=1 */
  PTJSE |= (unsigned char)0x1F;                      
  /* PTADS: PTADS7=0,PTADS6=0,PTADS5=0,PTADS4=0,PTADS3=0,PTADS2=0,PTADS1=0,PTADS0=0 */
  PTADS = 0x00;                                      
  /* PTBDS: PTBDS7=0,PTBDS6=0,PTBDS5=0,PTBDS4=0,PTBDS3=0,PTBDS2=0,PTBDS1=0,PTBDS0=0 */
  PTBDS = 0x00;                                      
  /* PTCDS: PTCDS7=0,PTCDS6=0,PTCDS5=0,PTCDS4=0,PTCDS3=0,PTCDS2=0,PTCDS1=0,PTCDS0=0 */
  PTCDS = 0x00;                                      
  /* PTDDS: PTDDS7=0,PTDDS6=0,PTDDS5=0,PTDDS4=0,PTDDS3=0,PTDDS2=0,PTDDS1=0,PTDDS0=0 */
  PTDDS = 0x00;                                      
  /* PTEDS: PTEDS7=0,PTEDS6=0,PTEDS5=0,PTEDS4=0,PTEDS3=0,PTEDS2=0,PTEDS1=0,PTEDS0=0 */
  PTEDS = 0x00;                                      
  /* PTFDS: PTFDS7=0,PTFDS6=0,PTFDS5=0,PTFDS4=0,PTFDS3=0,PTFDS2=0,PTFDS1=0,PTFDS0=0 */
  PTFDS = 0x00;                                      
  /* PTGDS: PTGDS7=0,PTGDS6=0,PTGDS5=0,PTGDS4=0,PTGDS3=0,PTGDS2=0,PTGDS1=0,PTGDS0=0 */
  PTGDS = 0x00;                                      
  /* PTHDS: PTHDS4=0,PTHDS3=0,PTHDS2=0,PTHDS1=0,PTHDS0=0 */
  PTHDS = 0x00;                                      
  /* PTJDS: PTJDS4=0,PTJDS3=0,PTJDS2=0,PTJDS1=0,PTJDS0=0 */
  PTJDS = 0x00;                                      
  /* PTAIFE: PTAIFE7=1,PTAIFE6=1,PTAIFE5=1,PTAIFE4=1,PTAIFE3=1,PTAIFE2=1,PTAIFE1=1,PTAIFE0=1 */
  PTAIFE = 0xFF;                                      
  /* PTBIFE: PTBIFE7=1,PTBIFE6=1,PTBIFE5=1,PTBIFE4=1,PTBIFE3=1,PTBIFE2=1,PTBIFE1=1,PTBIFE0=1 */
  PTBIFE = 0xFF;                                      
  /* PTCIFE: PTCIFE7=1,PTCIFE6=1,PTCIFE5=1,PTCIFE4=1,PTCIFE3=1,PTCIFE2=1,PTCIFE1=1,PTCIFE0=1 */
  PTCIFE = 0xFF;                                      
  /* PTDIFE: PTDIFE7=1,PTDIFE6=1,PTDIFE5=1,PTDIFE4=1,PTDIFE3=1,PTDIFE2=1,PTDIFE1=1,PTDIFE0=1 */
  PTDIFE = 0xFF;                                      
  /* PTEIFE: PTEIFE7=1,PTEIFE6=1,PTEIFE5=1,PTEIFE4=1,PTEIFE3=1,PTEIFE2=1,PTEIFE1=1,PTEIFE0=1 */
  PTEIFE = 0xFF;                                      
  /* PTFIFE: PTFIFE7=1,PTFIFE6=1,PTFIFE5=1,PTFIFE4=1,PTFIFE3=1,PTFIFE2=1,PTFIFE1=1,PTFIFE0=1 */
  PTFIFE = 0xFF;                                      
  /* PTGIFE: PTGIFE7=1,PTGIFE6=1,PTGIFE5=1,PTGIFE4=1,PTGIFE3=1,PTGIFE2=1,PTGIFE1=1,PTGIFE0=1 */
  PTGIFE = 0xFF;                                      
  /* PTHIFE: PTHIFE4=1,PTHIFE3=1,PTHIFE2=1,PTHIFE1=1,PTHIFE0=1 */
  PTHIFE |= (unsigned char)0x1F;                      
  /* PTJIFE: PTJIFE4=1,PTJIFE3=1,PTJIFE2=1,PTJIFE1=1,PTJIFE0=1 */
  PTJIFE |= (unsigned char)0x1F;                      
  /* ### Init_GPIO init code */
  /* PTAD: PTAD4=1 */
  PTAD |= (unsigned char)0x10;                      
  /* PTADD: PTADD4=1 */
  PTADD |= (unsigned char)0x10;                      
  /* ### Init_SPI init code */
  /* SPI1C1: SPIE=0,SPE=0,SPTIE=0,MSTR=0,CPOL=0,CPHA=0,SSOE=0,LSBFE=0 */
  SPI1C1 = 0x00;                       /* All interrupt flags in SPIxS register are reset when the SPI1 module is disabled. */
  /* SPI1C2: SPMIE=0,SPIMODE=0,MODFEN=0,BIDIROE=0,SPISWAI=0,SPC0=0 */
  SPI1C2 = 0x00;                                      
  /* SPI1BR: SPPR2=0,SPPR1=1,SPPR0=1,SPR2=0,SPR1=1,SPR0=1 */
  SPI1BR = 0x33;                                      
  /* SPI1M: Bit15=0,Bit14=0,Bit13=0,Bit12=0,Bit11=0,Bit10=0,Bit9=0,Bit8=0,Bit7=0,Bit6=0,Bit5=0,Bit4=0,Bit3=0,Bit2=0,Bit1=0,Bit0=0 */
  SPI1M = 0x00U;                            
  /* SPI1C1: SPIE=0,SPE=0,SPTIE=0,MSTR=1,CPOL=0,CPHA=0,SSOE=0,LSBFE=0 */
  SPI1C1 = 0x10;                                      
  /* ### */
  asm {                                /* Set Interrupt level 0 */
    move.w SR,D0;
    andi.l #0xF8FF,D0;
    move.w D0,SR;
  }
} /*MCU_init*/


/*
** ===================================================================
**     Interrupt handler : isr_default
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isr_default(void)
{
  /* Write your interrupt code here ... */

}
/* end of isr_default */


/*
** ===================================================================
**     Interrupt handler : isrVspi1
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVspi1(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVspi1 */



/* Initialization of the CPU registers in FLASH */

/* NVPROT: FPS6=1,FPS5=1,FPS4=1,FPS3=1,FPS2=1,FPS1=1,FPS0=1,FPOPEN=1 */
unsigned char NVPROT_INIT @0x0000040D = 0xFF;

/* NVOPT: KEYEN1=0,KEYEN0=1,SEC1=1,SEC0=1 */
unsigned char NVOPT_INIT @0x0000040F = 0x7F;




#ifdef __cplusplus
extern "C" {
#endif
extern void _startup(void);
extern unsigned long far _SP_INIT[];

#ifdef __cplusplus
}
#endif

/* Interrupt vector table */
#ifndef UNASSIGNED_ISR
  #define UNASSIGNED_ISR isr_default   /* unassigned interrupt service routine */
#endif

                                                                /*Address    Lvl Pri */
void (*const vector_0)(void)   @INITSP       = (void(*const )(void))_SP_INIT; /*0x00000000 -   - */
void (*const vector_1)(void)   @INITPC       = _startup;        /*0x00000004 -   - */
void (*const vector_2)(void)   @Vaccerr      = UNASSIGNED_ISR;  /*0x00000008 -   - */
void (*const vector_3)(void)   @Vadderr      = UNASSIGNED_ISR;  /*0x0000000C -   - */
void (*const vector_4)(void)   @Viinstr      = UNASSIGNED_ISR;  /*0x00000010 -   - */
void (*const vector_5)(void)   @VReserved5   = UNASSIGNED_ISR;  /*0x00000014 -   - */
void (*const vector_6)(void)   @VReserved6   = UNASSIGNED_ISR;  /*0x00000018 -   - */
void (*const vector_7)(void)   @VReserved7   = UNASSIGNED_ISR;  /*0x0000001C -   - */
void (*const vector_8)(void)   @Vprviol      = UNASSIGNED_ISR;  /*0x00000020 -   - */
void (*const vector_9)(void)   @Vtrace       = UNASSIGNED_ISR;  /*0x00000024 -   - */
void (*const vector_10)(void)  @Vunilaop     = UNASSIGNED_ISR;  /*0x00000028 -   - */
void (*const vector_11)(void)  @Vunilfop     = UNASSIGNED_ISR;  /*0x0000002C -   - */
void (*const vector_12)(void)  @Vdbgi        = UNASSIGNED_ISR;  /*0x00000030 -   - */
void (*const vector_13)(void)  @VReserved13  = UNASSIGNED_ISR;  /*0x00000034 -   - */
void (*const vector_14)(void)  @Vferror      = UNASSIGNED_ISR;  /*0x00000038 -   - */
void (*const vector_15)(void)  @VReserved15  = UNASSIGNED_ISR;  /*0x0000003C -   - */
void (*const vector_16)(void)  @VReserved16  = UNASSIGNED_ISR;  /*0x00000040 -   - */
void (*const vector_17)(void)  @VReserved17  = UNASSIGNED_ISR;  /*0x00000044 -   - */
void (*const vector_18)(void)  @VReserved18  = UNASSIGNED_ISR;  /*0x00000048 -   - */
void (*const vector_19)(void)  @VReserved19  = UNASSIGNED_ISR;  /*0x0000004C -   - */
void (*const vector_20)(void)  @VReserved20  = UNASSIGNED_ISR;  /*0x00000050 -   - */
void (*const vector_21)(void)  @VReserved21  = UNASSIGNED_ISR;  /*0x00000054 -   - */
void (*const vector_22)(void)  @VReserved22  = UNASSIGNED_ISR;  /*0x00000058 -   - */
void (*const vector_23)(void)  @VReserved23  = UNASSIGNED_ISR;  /*0x0000005C -   - */
void (*const vector_24)(void)  @Vspuri       = UNASSIGNED_ISR;  /*0x00000060 -   - */
void (*const vector_25)(void)  @VReserved25  = UNASSIGNED_ISR;  /*0x00000064 -   - */
void (*const vector_26)(void)  @VReserved26  = UNASSIGNED_ISR;  /*0x00000068 -   - */
void (*const vector_27)(void)  @VReserved27  = UNASSIGNED_ISR;  /*0x0000006C -   - */
void (*const vector_28)(void)  @VReserved28  = UNASSIGNED_ISR;  /*0x00000070 -   - */
void (*const vector_29)(void)  @VReserved29  = UNASSIGNED_ISR;  /*0x00000074 -   - */
void (*const vector_30)(void)  @VReserved30  = UNASSIGNED_ISR;  /*0x00000078 -   - */
void (*const vector_31)(void)  @VReserved31  = UNASSIGNED_ISR;  /*0x0000007C -   - */
void (*const vector_32)(void)  @Vtrap0       = UNASSIGNED_ISR;  /*0x00000080 -   - */
void (*const vector_33)(void)  @Vtrap1       = UNASSIGNED_ISR;  /*0x00000084 -   - */
void (*const vector_34)(void)  @Vtrap2       = UNASSIGNED_ISR;  /*0x00000088 -   - */
void (*const vector_35)(void)  @Vtrap3       = UNASSIGNED_ISR;  /*0x0000008C -   - */
void (*const vector_36)(void)  @Vtrap4       = UNASSIGNED_ISR;  /*0x00000090 -   - */
void (*const vector_37)(void)  @Vtrap5       = UNASSIGNED_ISR;  /*0x00000094 -   - */
void (*const vector_38)(void)  @Vtrap6       = UNASSIGNED_ISR;  /*0x00000098 -   - */
void (*const vector_39)(void)  @Vtrap7       = UNASSIGNED_ISR;  /*0x0000009C -   - */
void (*const vector_40)(void)  @Vtrap8       = UNASSIGNED_ISR;  /*0x000000A0 -   - */
void (*const vector_41)(void)  @Vtrap9       = UNASSIGNED_ISR;  /*0x000000A4 -   - */
void (*const vector_42)(void)  @Vtrap10      = UNASSIGNED_ISR;  /*0x000000A8 -   - */
void (*const vector_43)(void)  @Vtrap11      = UNASSIGNED_ISR;  /*0x000000AC -   - */
void (*const vector_44)(void)  @Vtrap12      = UNASSIGNED_ISR;  /*0x000000B0 -   - */
void (*const vector_45)(void)  @Vtrap13      = UNASSIGNED_ISR;  /*0x000000B4 -   - */
void (*const vector_46)(void)  @Vtrap14      = UNASSIGNED_ISR;  /*0x000000B8 -   - */
void (*const vector_47)(void)  @Vtrap15      = UNASSIGNED_ISR;  /*0x000000BC -   - */
void (*const vector_48)(void)  @VReserved48  = UNASSIGNED_ISR;  /*0x000000C0 -   - */
void (*const vector_49)(void)  @VReserved49  = UNASSIGNED_ISR;  /*0x000000C4 -   - */
void (*const vector_50)(void)  @VReserved50  = UNASSIGNED_ISR;  /*0x000000C8 -   - */
void (*const vector_51)(void)  @VReserved51  = UNASSIGNED_ISR;  /*0x000000CC -   - */
void (*const vector_52)(void)  @VReserved52  = UNASSIGNED_ISR;  /*0x000000D0 -   - */
void (*const vector_53)(void)  @VReserved53  = UNASSIGNED_ISR;  /*0x000000D4 -   - */
void (*const vector_54)(void)  @VReserved54  = UNASSIGNED_ISR;  /*0x000000D8 -   - */
void (*const vector_55)(void)  @VReserved55  = UNASSIGNED_ISR;  /*0x000000DC -   - */
void (*const vector_56)(void)  @VReserved56  = UNASSIGNED_ISR;  /*0x000000E0 -   - */
void (*const vector_57)(void)  @VReserved57  = UNASSIGNED_ISR;  /*0x000000E4 -   - */
void (*const vector_58)(void)  @VReserved58  = UNASSIGNED_ISR;  /*0x000000E8 -   - */
void (*const vector_59)(void)  @VReserved59  = UNASSIGNED_ISR;  /*0x000000EC -   - */
void (*const vector_60)(void)  @VReserved60  = UNASSIGNED_ISR;  /*0x000000F0 -   - */
void (*const vector_61)(void)  @Vunsinstr    = UNASSIGNED_ISR;  /*0x000000F4 -   - */
void (*const vector_62)(void)  @VReserved62  = UNASSIGNED_ISR;  /*0x000000F8 -   - */
void (*const vector_63)(void)  @VReserved63  = UNASSIGNED_ISR;  /*0x000000FC -   - */
void (*const vector_64)(void)  @Virq         = UNASSIGNED_ISR;  /*0x00000100 -   - */
void (*const vector_65)(void)  @Vlvd         = UNASSIGNED_ISR;  /*0x00000104 -   - */
void (*const vector_66)(void)  @Vlol         = UNASSIGNED_ISR;  /*0x00000108 -   - */
void (*const vector_67)(void)  @Vspi1        = isrVspi1;        /*0x0000010C 6   5 */
void (*const vector_68)(void)  @Vspi2        = UNASSIGNED_ISR;  /*0x00000110 -   - */
void (*const vector_69)(void)  @Vusb         = UNASSIGNED_ISR;  /*0x00000114 -   - */
void (*const vector_70)(void)  @VReserved70  = UNASSIGNED_ISR;  /*0x00000118 -   - */
void (*const vector_71)(void)  @Vtpm1ch0     = UNASSIGNED_ISR;  /*0x0000011C -   - */
void (*const vector_72)(void)  @Vtpm1ch1     = UNASSIGNED_ISR;  /*0x00000120 -   - */
void (*const vector_73)(void)  @Vtpm1ch2     = UNASSIGNED_ISR;  /*0x00000124 -   - */
void (*const vector_74)(void)  @Vtpm1ch3     = UNASSIGNED_ISR;  /*0x00000128 -   - */
void (*const vector_75)(void)  @Vtpm1ch4     = UNASSIGNED_ISR;  /*0x0000012C -   - */
void (*const vector_76)(void)  @Vtpm1ch5     = UNASSIGNED_ISR;  /*0x00000130 -   - */
void (*const vector_77)(void)  @Vtpm1ovf     = UNASSIGNED_ISR;  /*0x00000134 -   - */
void (*const vector_78)(void)  @Vtpm2ch0     = UNASSIGNED_ISR;  /*0x00000138 -   - */
void (*const vector_79)(void)  @Vtpm2ch1     = UNASSIGNED_ISR;  /*0x0000013C -   - */
void (*const vector_80)(void)  @Vtpm2ovf     = UNASSIGNED_ISR;  /*0x00000140 -   - */
void (*const vector_81)(void)  @Vsci1err     = UNASSIGNED_ISR;  /*0x00000144 -   - */
void (*const vector_82)(void)  @Vsci1rx      = UNASSIGNED_ISR;  /*0x00000148 -   - */
void (*const vector_83)(void)  @Vsci1tx      = UNASSIGNED_ISR;  /*0x0000014C -   - */
void (*const vector_84)(void)  @Vsci2err     = UNASSIGNED_ISR;  /*0x00000150 -   - */
void (*const vector_85)(void)  @Vsci2rx      = UNASSIGNED_ISR;  /*0x00000154 -   - */
void (*const vector_86)(void)  @Vsci2tx      = UNASSIGNED_ISR;  /*0x00000158 -   - */
void (*const vector_87)(void)  @Vkeyboard    = UNASSIGNED_ISR;  /*0x0000015C -   - */
void (*const vector_88)(void)  @Vadc         = UNASSIGNED_ISR;  /*0x00000160 -   - */
void (*const vector_89)(void)  @Vacmpx       = UNASSIGNED_ISR;  /*0x00000164 -   - */
void (*const vector_90)(void)  @Viic1x       = UNASSIGNED_ISR;  /*0x00000168 -   - */
void (*const vector_91)(void)  @Vrtc         = UNASSIGNED_ISR;  /*0x0000016C -   - */
void (*const vector_92)(void)  @Viic2x       = UNASSIGNED_ISR;  /*0x00000170 -   - */
void (*const vector_93)(void)  @Vcmt         = UNASSIGNED_ISR;  /*0x00000174 -   - */
void (*const vector_94)(void)  @Vcanwu       = UNASSIGNED_ISR;  /*0x00000178 -   - */
void (*const vector_95)(void)  @Vcanerr      = UNASSIGNED_ISR;  /*0x0000017C -   - */
void (*const vector_96)(void)  @Vcanrx       = UNASSIGNED_ISR;  /*0x00000180 -   - */
void (*const vector_97)(void)  @Vcantx       = UNASSIGNED_ISR;  /*0x00000184 -   - */
void (*const vector_98)(void)  @Vrnga        = UNASSIGNED_ISR;  /*0x00000188 -   - */
void (*const vector_99)(void)  @VReserved99  = UNASSIGNED_ISR;  /*0x0000018C -   - */
void (*const vector_100)(void) @VReserved100 = UNASSIGNED_ISR;  /*0x00000190 -   - */
void (*const vector_101)(void) @VReserved101 = UNASSIGNED_ISR;  /*0x00000194 -   - */
void (*const vector_102)(void) @VReserved102 = UNASSIGNED_ISR;  /*0x00000198 -   - */
void (*const vector_103)(void) @VReserved103 = UNASSIGNED_ISR;  /*0x0000019C -   - */
void (*const vector_104)(void) @VL7swi       = UNASSIGNED_ISR;  /*0x000001A0 -   - */
void (*const vector_105)(void) @VL6swi       = UNASSIGNED_ISR;  /*0x000001A4 -   - */
void (*const vector_106)(void) @VL5swi       = UNASSIGNED_ISR;  /*0x000001A8 -   - */
void (*const vector_107)(void) @VL4swi       = UNASSIGNED_ISR;  /*0x000001AC -   - */
void (*const vector_108)(void) @VL3swi       = UNASSIGNED_ISR;  /*0x000001B0 -   - */
void (*const vector_109)(void) @VL2swi       = UNASSIGNED_ISR;  /*0x000001B4 -   - */
void (*const vector_110)(void) @VL1swi       = UNASSIGNED_ISR;  /*0x000001B8 -   - */





/*
** ===================================================================
**     Interrupt handler : isrVkeyboard
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
__interrupt void isrVkeyboard(void)
{
  // Write your interrupt code here ... 

}
*/
/* end of isrVkeyboard */


/*
** ===================================================================
**     Interrupt handler : isrVtpm3ovf
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
__interrupt void isrVtpm3ovf(void)
{
  // Write your interrupt code here ... 

}

/* end of isrVtpm3ovf */


/*
** ===================================================================
**     Interrupt handler : isrVsci1tx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVsci1tx(void)
{
  // Write your interrupt code here ... 

}

/* end of isrVsci1tx */


/*
** ===================================================================
**     Interrupt handler : isrVsci1rx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
__interrupt void isrVsci1rx(void)
{

// Write your interrupt code here ... 
  
  SCI1S1; //reconoce la interrupción
rx_dato = SCI1D;//lea caracter que entro


}
*/
/* end of isrVsci1rx */


/*
** ===================================================================
**     Interrupt handler : isrVsci1err
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVsci1err(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVsci1err */


/*
** ===================================================================
**     Interrupt handler : isrVftm1fault
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVftm1fault(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVftm1fault */


/*
** ===================================================================
**     Interrupt handler : isrVadc1
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
__interrupt void isrVadc1(void)
{
  // Write your interrupt code here ... 

}
*/
/* end of isrVadc1 */


/*
** ===================================================================
**     Interrupt handler : isrVsci2tx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVsci2tx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVsci2tx */


/*
** ===================================================================
**     Interrupt handler : isrVsci2rx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVsci2rx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVsci2rx */


/*
** ===================================================================
**     Interrupt handler : isrVsci2err
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVsci2err(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVsci2err */


/*
** ===================================================================
**     Interrupt handler : isrVftm1ovf
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
__interrupt void isrVftm1ovf(void)
{
  // Write your interrupt code here ... 

}
*/
/* end of isrVftm1ovf */


/*
** ===================================================================
**     Interrupt handler : isrVirq
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
__interrupt void isrVirq(void)
{
  // Write your interrupt code here ... 

}
*/
/* end of isrVirq */

/* END MCUinit */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
